# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zj8z1ybRt6PLlowYs9O-_cMAKYnCvByT

#**Klasse ListKeeper inklusive allen Funktionen zum Aufrufen im Aufgaben Notebook**
"""

class ListKeeper:

  l1 = [1,2,3,4,5]
  l2 = [6,7,8,9,10]
  l3 = [11,12,13,14,15]

  d0 = {
    "l1": l1,
    "l2": l2,
    "l3": l3
    }

  def show():
    # returns all list names
    return d0
    pass

  def add(name, list):
    # adds a new list

    pass

  def delete(name):
    # deletes list

    pass

  def sort(name):
    # returns the sorted list name

    pass

  def append(name, list):
    # appends list to name

    pass